// Auto-generated by scripts/generate-tts.ts — do not edit manually.
// Updated by whisper-align.ts (word timings) and align-boundaries.ts (boundaryEnd).
// MiniMax TTS (speech-2.8-hd) + OpenAI Whisper word-level alignment +
// silencedetect-anchored sequence boundaries.
// Generated: 2026-04-19T10:03:13.834Z

import type { PartAlignment } from "../../../shared/lib/alignment-types";
export type { WordTiming, LineTiming, PartAlignment } from "../../../shared/lib/alignment-types";

export const alignmentManifest: Record<
  string,
  Record<string, PartAlignment>
> = {
  "cn": {
    "part1": {
      "file": "xiaomi-su7-bet/audio/cn/part1-full.mp3",
      "totalDuration": 50.148,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 9.279999732971191,
          "words": [
            {
              "text": "2013年，一个人坐在特斯拉工厂里，试驾Model S。",
              "start": 0,
              "end": 5.599999904632568
            },
            {
              "text": "那个人叫雷军。",
              "start": 5.599999904632568,
              "end": 6.699999809265137
            },
            {
              "text": "他说，他这辈子不会造车。",
              "start": 6.699999809265137,
              "end": 9.279999732971191
            }
          ],
          "boundaryEnd": 11.54405
        },
        "line2": {
          "startTime": 9.800000190734863,
          "endTime": 19.280000686645508,
          "words": [
            {
              "text": "八年之后，他食言了。",
              "start": 9.800000190734863,
              "end": 11.680000305175781
            },
            {
              "text": "52岁的亿万富翁，站在台上，宣布他要造车。",
              "start": 11.680000305175781,
              "end": 16.639999389648438
            },
            {
              "text": "他要押上自己一生的荣誉。",
              "start": 16.639999389648438,
              "end": 19.280000686645508
            }
          ],
          "boundaryEnd": 19.497349999999997
        },
        "line3": {
          "startTime": 19.8799991607666,
          "endTime": 28.1200008392334,
          "words": [
            {
              "text": "西方媒体的标题，清一色地写着同一句话。",
              "start": 19.8799991607666,
              "end": 23.040000915527344
            },
            {
              "text": "又一家手机公司搞汽车。",
              "start": 23.040000915527344,
              "end": 25.399999618530273
            },
            {
              "text": "和苹果一样，注定失败。",
              "start": 25.399999618530273,
              "end": 28.1200008392334
            }
          ],
          "boundaryEnd": 28.4103
        },
        "line4": {
          "startTime": 28.559999465942383,
          "endTime": 33.20000076293945,
          "words": [
            {
              "text": "但他们没看见一件事。",
              "start": 28.559999465942383,
              "end": 29.979999542236328
            },
            {
              "text": "雷军不是来试试水的。",
              "start": 29.979999542236328,
              "end": 32.2400016784668
            },
            {
              "text": "他是来赌命的。",
              "start": 32.2400016784668,
              "end": 33.20000076293945
            }
          ],
          "boundaryEnd": 32.07325
        },
        "line5": {
          "startTime": 33.560001373291016,
          "endTime": 40.97999954223633,
          "words": [
            {
              "text": "他的原话是这样。",
              "start": 33.560001373291016,
              "end": 34.70000076293945
            },
            {
              "text": "这是我人生最后一个大的创业项目。",
              "start": 34.70000076293945,
              "end": 37.20000076293945
            },
            {
              "text": "我愿意押上全部声誉，为小米汽车而战。",
              "start": 37.20000076293945,
              "end": 40.97999954223633
            }
          ],
          "boundaryEnd": 41.14905
        },
        "line6": {
          "startTime": 41.58000183105469,
          "endTime": 48.220001220703125,
          "words": [
            {
              "text": "一个能说出押上全部声誉的CEO，他看见了什么。",
              "start": 41.58000183105469,
              "end": 45.31999969482422
            },
            {
              "text": "西方没看见的，到底是什么。",
              "start": 45.31999969482422,
              "end": 48.220001220703125
            }
          ],
          "boundaryEnd": 47.27485
        },
        "line7": {
          "startTime": 48.540000915527344,
          "endTime": 50,
          "words": [
            {
              "text": "这就是我们今天要拆的故事。",
              "start": 48.540000915527344,
              "end": 50
            }
          ]
        }
      }
    },
    "part3": {
      "file": "xiaomi-su7-bet/audio/cn/part3-full.mp3",
      "totalDuration": 49.968,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 4.480000019073486,
          "words": [
            {
              "text": "2024年3月28日，小米SU7正式发布。",
              "start": 0,
              "end": 4.480000019073486
            }
          ],
          "boundaryEnd": 6.651
        },
        "line2": {
          "startTime": 4.659999847412109,
          "endTime": 10.899999618530273,
          "words": [
            {
              "text": "起售价21万5千9。",
              "start": 4.659999847412109,
              "end": 6.5
            },
            {
              "text": "顶配29万9千9。",
              "start": 6.5,
              "end": 8.699999809265137
            },
            {
              "text": "只有保时捷Taycan的三分之一。",
              "start": 8.699999809265137,
              "end": 10.899999618530273
            }
          ],
          "boundaryEnd": 11.113
        },
        "line3": {
          "startTime": 11.300000190734863,
          "endTime": 14.300000190734863,
          "words": [
            {
              "text": "但参数不是三分之一。",
              "start": 11.300000190734863,
              "end": 12.880000114440918
            },
            {
              "text": "是全面对标。",
              "start": 12.880000114440918,
              "end": 14.300000190734863
            }
          ],
          "boundaryEnd": 17.239800000000002
        },
        "line4": {
          "startTime": 14.9399995803833,
          "endTime": 21.18000030517578,
          "words": [
            {
              "text": "零百加速2点78秒。",
              "start": 14.9399995803833,
              "end": 17.059999465942383
            },
            {
              "text": "最高时速265公里。",
              "start": 17.059999465942383,
              "end": 19.6200008392334
            },
            {
              "text": "续航800公里。",
              "start": 19.6200008392334,
              "end": 21.18000030517578
            }
          ],
          "boundaryEnd": 22.6267
        },
        "line5": {
          "startTime": 21.799999237060547,
          "endTime": 29.979999542236328,
          "words": [
            {
              "text": "这是什么概念。",
              "start": 21.799999237060547,
              "end": 22.399999618530273
            },
            {
              "text": "五年之前，全世界只有三款车能做到这组数据。",
              "start": 22.399999618530273,
              "end": 28.020000457763672
            },
            {
              "text": "奔驰，保时捷，特斯拉Plaid。",
              "start": 28.020000457763672,
              "end": 29.979999542236328
            }
          ],
          "boundaryEnd": 31.642400000000002
        },
        "line6": {
          "startTime": 32.29999923706055,
          "endTime": 39.900001525878906,
          "words": [
            {
              "text": "现在，一家从2021年才开始造车的公司，做到了。",
              "start": 32.29999923706055,
              "end": 37.29999923706055
            },
            {
              "text": "起售价只有它们的五分之一。",
              "start": 37.29999923706055,
              "end": 39.900001525878906
            }
          ],
          "boundaryEnd": 39.773700000000005
        },
        "line7": {
          "startTime": 40.060001373291016,
          "endTime": 49.63999938964844,
          "words": [
            {
              "text": "雷军在发布会上，停顿了足足三秒。",
              "start": 40.060001373291016,
              "end": 43.400001525878906
            },
            {
              "text": "他说。",
              "start": 43.400001525878906,
              "end": 44.18000030517578
            },
            {
              "text": "这不是我们一家公司的胜利。",
              "start": 44.18000030517578,
              "end": 47.13999938964844
            },
            {
              "text": "这是整个中国制造业的胜利。",
              "start": 47.13999938964844,
              "end": 49.63999938964844
            }
          ]
        }
      }
    },
    "part4": {
      "file": "xiaomi-su7-bet/audio/cn/part4-full.mp3",
      "totalDuration": 51.768,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 4.980000019073486,
          "words": [
            {
              "text": "SU7发布后的24小时，订单突破了八万八千台。",
              "start": 0,
              "end": 4.980000019073486
            }
          ],
          "boundaryEnd": 8.211110000000001
        },
        "line2": {
          "startTime": 5.300000190734863,
          "endTime": 11.819999694824219,
          "words": [
            {
              "text": "西方分析师开始改口。",
              "start": 5.300000190734863,
              "end": 7.099999904632568
            },
            {
              "text": "他们说。",
              "start": 7.099999904632568,
              "end": 8.020000457763672
            },
            {
              "text": "或许这不是又一家手机公司搞汽车。",
              "start": 8.020000457763672,
              "end": 11.819999694824219
            }
          ],
          "boundaryEnd": 14.237649999999999
        },
        "line3": {
          "startTime": 12.34000015258789,
          "endTime": 18.81999969482422,
          "words": [
            {
              "text": "苹果十年造不出来的东西，小米三年搞定了。",
              "start": 12.34000015258789,
              "end": 16.100000381469727
            },
            {
              "text": "答案藏在两个CEO的不同选择里。",
              "start": 16.100000381469727,
              "end": 18.81999969482422
            }
          ],
          "boundaryEnd": 18.66785
        },
        "line4": {
          "startTime": 19.020000457763672,
          "endTime": 25.399999618530273,
          "words": [
            {
              "text": "库克走的是稳妥路线。",
              "start": 19.020000457763672,
              "end": 21.079999923706055
            },
            {
              "text": "给股东讲一个安全的故事。",
              "start": 21.079999923706055,
              "end": 23.059999465942383
            },
            {
              "text": "项目不赚钱，就砍掉。",
              "start": 23.059999465942383,
              "end": 25.399999618530273
            }
          ],
          "boundaryEnd": 25.89365
        },
        "line5": {
          "startTime": 25.8799991607666,
          "endTime": 32.79999923706055,
          "words": [
            {
              "text": "雷军押的是身家。",
              "start": 25.8799991607666,
              "end": 28.059999465942383
            },
            {
              "text": "赌上全部声誉。",
              "start": 28.059999465942383,
              "end": 29.540000915527344
            },
            {
              "text": "不成功，就永远翻不了身。",
              "start": 29.540000915527344,
              "end": 32.79999923706055
            }
          ],
          "boundaryEnd": 33.0998
        },
        "line6": {
          "startTime": 33.31999969482422,
          "endTime": 40.380001068115234,
          "words": [
            {
              "text": "这是两种CEO模式的对撞。",
              "start": 33.31999969482422,
              "end": 35.41999816894531
            },
            {
              "text": "一种，是职业经理人。",
              "start": 35.41999816894531,
              "end": 38.2599983215332
            },
            {
              "text": "另一种，是创始人All in。",
              "start": 38.2599983215332,
              "end": 40.380001068115234
            }
          ],
          "boundaryEnd": 40.6884
        },
        "line7": {
          "startTime": 41.099998474121094,
          "endTime": 51.41999816894531,
          "words": [
            {
              "text": "所以当有人问，雷军是不是下一个乔布斯。",
              "start": 41.099998474121094,
              "end": 44.20000076293945
            },
            {
              "text": "我觉得这个问题问错了。",
              "start": 44.20000076293945,
              "end": 46.540000915527344
            },
            {
              "text": "真正的问题是，美国今天还能不能，再生出一个雷军式的CEO。",
              "start": 46.540000915527344,
              "end": 51.41999816894531
            }
          ]
        }
      }
    },
    "part2": {
      "file": "xiaomi-su7-bet/audio/cn/part2-full.mp3",
      "totalDuration": 53.64,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 8.5600004196167,
          "words": [
            {
              "text": "2021年春天，小米办公室开始流失工程师。",
              "start": 0,
              "end": 4.239999771118164
            },
            {
              "text": "他们不是跳槽去字节或者腾讯。",
              "start": 4.239999771118164,
              "end": 6.880000114440918
            },
            {
              "text": "他们是去造车。",
              "start": 6.880000114440918,
              "end": 8.5600004196167
            }
          ],
          "boundaryEnd": 8.83025
        },
        "line2": {
          "startTime": 8.9399995803833,
          "endTime": 18.18000030517578,
          "words": [
            {
              "text": "一年之内，超过三千四百个工程师，加入了小米汽车团队。",
              "start": 8.9399995803833,
              "end": 13.600000381469727
            },
            {
              "text": "里面有华为，蔚来，宝马，吉利的核心骨干。",
              "start": 13.600000381469727,
              "end": 18.18000030517578
            }
          ],
          "boundaryEnd": 19.747700000000002
        },
        "line3": {
          "startTime": 18.18000030517578,
          "endTime": 27.68000030517578,
          "words": [
            {
              "text": "在硅谷，工程师辞职，是为了去AI创业公司。",
              "start": 18.18000030517578,
              "end": 23.100000381469727
            },
            {
              "text": "在中国，他们辞职，是为了去做电动车。",
              "start": 23.100000381469727,
              "end": 27.68000030517578
            }
          ],
          "boundaryEnd": 29.8603
        },
        "line4": {
          "startTime": 27.899999618530273,
          "endTime": 33.84000015258789,
          "words": [
            {
              "text": "原因很简单。",
              "start": 27.899999618530273,
              "end": 28.600000381469727
            },
            {
              "text": "在中国，一台电动车，不是一个产品。",
              "start": 28.600000381469727,
              "end": 32.2599983215332
            },
            {
              "text": "它是一个生态的入口。",
              "start": 32.2599983215332,
              "end": 33.84000015258789
            }
          ],
          "boundaryEnd": 31.1999
        },
        "line5": {
          "startTime": 34.2400016784668,
          "endTime": 40.459999084472656,
          "words": [
            {
              "text": "手机，汽车，家电，操作系统，全部连在一起。",
              "start": 34.2400016784668,
              "end": 38.91999816894531
            },
            {
              "text": "这叫澎湃OS。",
              "start": 38.91999816894531,
              "end": 40.459999084472656
            }
          ],
          "boundaryEnd": 40.662
        },
        "line6": {
          "startTime": 41.040000915527344,
          "endTime": 46.939998626708984,
          "words": [
            {
              "text": "苹果做了整整十年的造车项目。",
              "start": 41.040000915527344,
              "end": 43.279998779296875
            },
            {
              "text": "烧掉了一百亿美元。",
              "start": 43.279998779296875,
              "end": 44.84000015258789
            },
            {
              "text": "然后放弃了。",
              "start": 44.84000015258789,
              "end": 46.939998626708984
            }
          ],
          "boundaryEnd": 48.2821
        },
        "line7": {
          "startTime": 47.060001373291016,
          "endTime": 53.47999954223633,
          "words": [
            {
              "text": "小米只用了三年，就把车开上了交付线。",
              "start": 47.060001373291016,
              "end": 50.119998931884766
            },
            {
              "text": "因为整个中国供应链，在推着他往前跑。",
              "start": 50.119998931884766,
              "end": 53.47999954223633
            }
          ]
        }
      }
    }
  },
  "en": {
    "part1": {
      "file": "xiaomi-su7-bet/audio/en/part1-full.mp3",
      "totalDuration": 60.912,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 10.5,
          "words": [
            {
              "text": "In 2013, a man sat in Tesla's factory, test-driving a Model S.",
              "start": 0,
              "end": 5.860000133514404
            },
            {
              "text": "His name was Lei Jun.",
              "start": 5.860000133514404,
              "end": 7.940000057220459
            },
            {
              "text": "He said he would never build cars.",
              "start": 7.940000057220459,
              "end": 10.5
            }
          ]
        },
        "line2": {
          "startTime": 11,
          "endTime": 22.1200008392334,
          "words": [
            {
              "text": "Eight years later, he broke his promise.",
              "start": 11,
              "end": 13.600000381469727
            },
            {
              "text": "At 52, a billionaire CEO stood on a stage and said he was doing it.",
              "start": 13.600000381469727,
              "end": 19.280000686645508
            },
            {
              "text": "And he was staking his reputation on it.",
              "start": 19.280000686645508,
              "end": 22.1200008392334
            }
          ]
        },
        "line3": {
          "startTime": 23.1200008392334,
          "endTime": 33.119998931884766,
          "words": [
            {
              "text": "Every Western headline ran with the same framing.",
              "start": 23.1200008392334,
              "end": 26.760000228881836
            },
            {
              "text": "Another phone company chasing cars.",
              "start": 26.760000228881836,
              "end": 30.5
            },
            {
              "text": "Destined to fail.",
              "start": 30.5,
              "end": 31.860000610351562
            },
            {
              "text": "Just like Apple.",
              "start": 31.860000610351562,
              "end": 33.119998931884766
            }
          ]
        },
        "line4": {
          "startTime": 34.68000030517578,
          "endTime": 40.02000045776367,
          "words": [
            {
              "text": "But they missed something.",
              "start": 34.68000030517578,
              "end": 36.20000076293945
            },
            {
              "text": "Lei Jun wasn't trying.",
              "start": 36.20000076293945,
              "end": 38.099998474121094
            },
            {
              "text": "He was going all in.",
              "start": 38.099998474121094,
              "end": 40.02000045776367
            }
          ]
        },
        "line5": {
          "startTime": 40.380001068115234,
          "endTime": 49.36000061035156,
          "words": [
            {
              "text": "His exact words were these.",
              "start": 40.380001068115234,
              "end": 42.31999969482422
            },
            {
              "text": "This is my final major entrepreneurial project.",
              "start": 42.31999969482422,
              "end": 46
            },
            {
              "text": "I'm willing to stake my entire reputation on it.",
              "start": 46,
              "end": 49.36000061035156
            }
          ]
        },
        "line6": {
          "startTime": 49.900001525878906,
          "endTime": 57.65999984741211,
          "words": [
            {
              "text": "A CEO who stakes his entire reputation.",
              "start": 49.900001525878906,
              "end": 53.099998474121094
            },
            {
              "text": "What did he see.",
              "start": 53.099998474121094,
              "end": 55.34000015258789
            },
            {
              "text": "What did the West miss.",
              "start": 55.34000015258789,
              "end": 57.65999984741211
            }
          ]
        },
        "line7": {
          "startTime": 58.2599983215332,
          "endTime": 60.63999938964844,
          "words": [
            {
              "text": "That's the story we're unpacking today.",
              "start": 58.2599983215332,
              "end": 60.63999938964844
            }
          ]
        }
      }
    },
    "part2": {
      "file": "xiaomi-su7-bet/audio/en/part2-full.mp3",
      "totalDuration": 58.536,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 8.65999984741211,
          "words": [
            {
              "text": "Spring 2021.",
              "start": 0,
              "end": 1.6790109561694848
            },
            {
              "text": "Xiaomi's offices start losing engineers.",
              "start": 1.6790109561694848,
              "end": 4.780219759259905
            },
            {
              "text": "Not to ByteDance or Tencent.",
              "start": 4.780219759259905,
              "end": 6.909890221276875
            },
            {
              "text": "They're leaving to build cars.",
              "start": 6.909890221276875,
              "end": 8.65999984741211
            }
          ]
        },
        "line2": {
          "startTime": 8.65999984741211,
          "endTime": 16.360000610351562,
          "words": [
            {
              "text": "Within a year, over thirty-four hundred engineers joined the Xiaomi EV team.",
              "start": 8.65999984741211,
              "end": 13.442222277323404
            },
            {
              "text": "Core talent from Huawei, Nio, BMW, Geely.",
              "start": 13.442222277323404,
              "end": 16.360000610351562
            }
          ]
        },
        "line3": {
          "startTime": 16.360000610351562,
          "endTime": 30.81999969482422,
          "words": [
            {
              "text": "In Silicon Valley, engineers quit to join AI startups.",
              "start": 16.360000610351562,
              "end": 21.76639563604422
            },
            {
              "text": "In China, they quit to build electric vehicles.",
              "start": 21.76639563604422,
              "end": 30.81999969482422
            }
          ]
        },
        "line4": {
          "startTime": 30.81999969482422,
          "endTime": 37.91999816894531,
          "words": [
            {
              "text": "The reason is simple.",
              "start": 30.81999969482422,
              "end": 32.785000801086426
            },
            {
              "text": "In China, an EV isn't a product.",
              "start": 32.785000801086426,
              "end": 34.736862706203084
            },
            {
              "text": "It's an entry point to an ecosystem.",
              "start": 34.736862706203084,
              "end": 37.91999816894531
            }
          ]
        },
        "line5": {
          "startTime": 38.619998931884766,
          "endTime": 45.52000045776367,
          "words": [
            {
              "text": "Phone.",
              "start": 38.619998931884766,
              "end": 38.823333225553
            },
            {
              "text": "Car.",
              "start": 38.823333225553,
              "end": 38.94533380175394
            },
            {
              "text": "Home appliances.",
              "start": 38.94533380175394,
              "end": 40.20542722429548
            },
            {
              "text": "Operating system.",
              "start": 40.20542722429548,
              "end": 41.54214263643537
            },
            {
              "text": "All of it connected.",
              "start": 41.54214263643537,
              "end": 43.348245519521285
            },
            {
              "text": "They call it HyperOS.",
              "start": 43.348245519521285,
              "end": 45.52000045776367
            }
          ]
        },
        "line6": {
          "startTime": 45.52000045776367,
          "endTime": 52.380001068115234,
          "words": [
            {
              "text": "Apple spent ten full years and ten billion dollars on its car project.",
              "start": 45.52000045776367,
              "end": 50.731831510302044
            },
            {
              "text": "Then walked away.",
              "start": 50.731831510302044,
              "end": 52.380001068115234
            }
          ]
        },
        "line7": {
          "startTime": 52.380001068115234,
          "endTime": 58.2400016784668,
          "words": [
            {
              "text": "Xiaomi did it in three.",
              "start": 52.380001068115234,
              "end": 54.571429116385325
            },
            {
              "text": "Because the entire Chinese supply chain was pushing him forward.",
              "start": 54.571429116385325,
              "end": 58.2400016784668
            }
          ]
        }
      }
    },
    "part3": {
      "file": "xiaomi-su7-bet/audio/en/part3-full.mp3",
      "totalDuration": 63.864,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 5.599999904632568,
          "words": [
            {
              "text": "March 28, 2024.",
              "start": 0,
              "end": 0.7105263241550379
            },
            {
              "text": "Xiaomi SU7 officially launches.",
              "start": 0.7105263241550379,
              "end": 5.599999904632568
            }
          ]
        },
        "line2": {
          "startTime": 5.599999904632568,
          "endTime": 16.979999542236328,
          "words": [
            {
              "text": "Starting price, twenty-one thousand US dollars.",
              "start": 5.599999904632568,
              "end": 9.508571079799108
            },
            {
              "text": "Top trim, under forty-two thousand.",
              "start": 9.508571079799108,
              "end": 13.514329340169718
            },
            {
              "text": "One third of a Porsche Taycan.",
              "start": 13.514329340169718,
              "end": 16.979999542236328
            }
          ]
        },
        "line3": {
          "startTime": 16.979999542236328,
          "endTime": 21.940000534057617,
          "words": [
            {
              "text": "But the specs aren't one-third.",
              "start": 16.979999542236328,
              "end": 19.127233911067883
            },
            {
              "text": "They match across the board.",
              "start": 19.127233911067883,
              "end": 21.940000534057617
            }
          ]
        },
        "line4": {
          "startTime": 21.940000534057617,
          "endTime": 31.979999542236328,
          "words": [
            {
              "text": "Zero to sixty in 2.",
              "start": 21.940000534057617,
              "end": 23.4472463303718
            },
            {
              "text": "78 seconds.",
              "start": 23.4472463303718,
              "end": 24.686666170756023
            },
            {
              "text": "Top speed 265 kilometers per hour.",
              "start": 24.686666170756023,
              "end": 29.455912490513015
            },
            {
              "text": "Range, 800 kilometers.",
              "start": 29.455912490513015,
              "end": 31.979999542236328
            }
          ]
        },
        "line5": {
          "startTime": 31.979999542236328,
          "endTime": 41.619998931884766,
          "words": [
            {
              "text": "Here's what that means.",
              "start": 31.979999542236328,
              "end": 33.797096006331905
            },
            {
              "text": "Five years ago, only three cars in the world hit those numbers.",
              "start": 33.797096006331905,
              "end": 38.4137338442004
            },
            {
              "text": "Mercedes.",
              "start": 38.4137338442004,
              "end": 39.56607578646752
            },
            {
              "text": "Porsche.",
              "start": 39.56607578646752,
              "end": 40.506849561418804
            },
            {
              "text": "Tesla Plaid.",
              "start": 40.506849561418804,
              "end": 41.619998931884766
            }
          ]
        },
        "line6": {
          "startTime": 42.400001525878906,
          "endTime": 49.720001220703125,
          "words": [
            {
              "text": "Now a company that started building cars in 2021 hits them too.",
              "start": 42.400001525878906,
              "end": 47.22999954223633
            },
            {
              "text": "At one-fifth the price.",
              "start": 47.22999954223633,
              "end": 49.720001220703125
            }
          ]
        },
        "line7": {
          "startTime": 49.720001220703125,
          "endTime": 63.47999954223633,
          "words": [
            {
              "text": "Lei Jun paused for three full seconds on stage.",
              "start": 49.720001220703125,
              "end": 55.155799448991026
            },
            {
              "text": "He said.",
              "start": 55.155799448991026,
              "end": 56.075168168845295
            },
            {
              "text": "This isn't a victory for one company.",
              "start": 56.075168168845295,
              "end": 58.82955508100457
            },
            {
              "text": "This is a victory for China's entire manufacturing base.",
              "start": 58.82955508100457,
              "end": 63.47999954223633
            }
          ]
        }
      }
    },
    "part4": {
      "file": "xiaomi-su7-bet/audio/en/part4-full.mp3",
      "totalDuration": 59.472,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 5.440000057220459,
          "words": [
            {
              "text": "Twenty-four hours after launch, SU7 had eighty-eight thousand pre-orders.",
              "start": 0,
              "end": 5.440000057220459
            }
          ]
        },
        "line2": {
          "startTime": 6.28000020980835,
          "endTime": 13.760000228881836,
          "words": [
            {
              "text": "Western analysts started walking back their takes.",
              "start": 6.28000020980835,
              "end": 8.880000114440918
            },
            {
              "text": "They said.",
              "start": 8.880000114440918,
              "end": 10
            },
            {
              "text": "Maybe this isn't just another phone company chasing cars.",
              "start": 10,
              "end": 13.760000228881836
            }
          ]
        },
        "line3": {
          "startTime": 14.319999694824219,
          "endTime": 21.719999313354492,
          "words": [
            {
              "text": "What Apple couldn't build in ten years, Xiaomi shipped in three.",
              "start": 14.319999694824219,
              "end": 18.059999465942383
            },
            {
              "text": "The answer sits in what each CEO chose to bet.",
              "start": 18.059999465942383,
              "end": 21.719999313354492
            }
          ]
        },
        "line4": {
          "startTime": 22.260000228881836,
          "endTime": 29.719999313354492,
          "words": [
            {
              "text": "Tim Cook played it safe.",
              "start": 22.260000228881836,
              "end": 23.780000686645508
            },
            {
              "text": "Told shareholders a steady story.",
              "start": 23.780000686645508,
              "end": 26.639999389648438
            },
            {
              "text": "Killed the project when it didn't pencil out.",
              "start": 26.639999389648438,
              "end": 29.719999313354492
            }
          ]
        },
        "line5": {
          "startTime": 30.559999465942383,
          "endTime": 35.65999984741211,
          "words": [
            {
              "text": "Lei Jun bet everything.",
              "start": 30.559999465942383,
              "end": 32
            },
            {
              "text": "His reputation on the line.",
              "start": 32,
              "end": 34.119998931884766
            },
            {
              "text": "No safety net.",
              "start": 34.119998931884766,
              "end": 35.65999984741211
            }
          ]
        },
        "line6": {
          "startTime": 36.13999938964844,
          "endTime": 45.060001373291016,
          "words": [
            {
              "text": "This is two CEO archetypes colliding.",
              "start": 36.13999938964844,
              "end": 39.02000045776367
            },
            {
              "text": "One, the professional manager.",
              "start": 39.02000045776367,
              "end": 41.34000015258789
            },
            {
              "text": "The other, the founder going all in.",
              "start": 41.34000015258789,
              "end": 45.060001373291016
            }
          ]
        },
        "line7": {
          "startTime": 45.119998931884766,
          "endTime": 59.18000030517578,
          "words": [
            {
              "text": "So when people ask, is Lei Jun the next Steve Jobs.",
              "start": 45.119998931884766,
              "end": 50.41999816894531
            },
            {
              "text": "I think that's the wrong question.",
              "start": 50.41999816894531,
              "end": 52.97999954223633
            },
            {
              "text": "The real question is, can America still produce a CEO willing to bet like Lei Jun.",
              "start": 52.97999954223633,
              "end": 59.18000030517578
            }
          ]
        }
      }
    }
  }
};
