/**
 * Auto-generated by scripts/allocate-broll.ts — do not edit manually.
 *
 * Algorithm: OpenAI text-embedding-3-small cosine similarity between each
 * narration line (CN+EN concat) and every frame description across all
 * source clips. Greedy longest-narration-first assignment under zero-
 * overlap + no-adjacency constraints. Windows sized to Whisper-accurate
 * narration durations from alignment-manifest.ts.
 *
 * Sources: research/xiaomi-su7-bet/sources.md
 * Validator: scripts/validate-broll.ts
 * Generated: 2026-04-19T07:58:52.972Z
 */

export type BrollEntry = { file: string; startFrom: number };

const V = (name: string) => `xiaomi-su7-bet/videos/${name}`;

export const brollManifest = {
  // ── part1 ──
  part1: {
    // sim=0.586 @1830s: Lei Jun stands on stage next to a large projection of a teal Xiaomi SU7 car. | Lei Jun, Xiaomi SU7
    p1_2013: { file: V("lei-jun-su7-launch.mp4"), startFrom: 1828 },
    // sim=0.563 @132s: A news anchor in a studio reports on Xiaomi's entry into the electric vehicle market. | Bloomberg Te
    p1_stage: { file: V("bloomberg-lei-jun.mp4"), startFrom: 130 },
    // sim=0.521 @1530s: Lei Jun, wearing a green suit, is on stage and playfully covering one eye with his hand. | Lei Jun, 
    p1_apple: { file: V("lei-jun-su7-launch.mp4"), startFrom: 1528 },
    // sim=0.580 @1200s: Lei Jun stands on stage presenting the teal Xiaomi SU7 car. | Lei Jun, Xiaomi SU7
    p1_closeup: { file: V("lei-jun-su7-launch.mp4"), startFrom: 1198 },
    // sim=0.283 @5700s: A partially disassembled blue car chassis is displayed on stage with a person standing near it. | Xi
    p1_contemplative: { file: V("lei-jun-su7-launch.mp4"), startFrom: 5698 },
  },

  // ── part2 ──
  part2: {
    // sim=0.584 @22s: A wide-angle view of a modern, automated Xiaomi EV factory floor featuring a large 9100t die-casting
    p2_offices: { file: V("xiaomi-factory.mp4"), startFrom: 20 },
    // sim=0.459 @552s: A female CNBC reporter stands in front of a building with a European Union flag, reporting on the Ch
    p2_engineers: { file: V("cnbc-china-ev.mp4"), startFrom: 550 },
    // sim=0.396 @160s: An aerial view shows the Xiaomi EV factory with rows of parked cars and a large manufacturing facili
    p2_sv_vs_cn: { file: V("xiaomi-factory.mp4"), startFrom: 158 },
    // sim=0.452 @765s: Tim Cook stands on stage to the left of a large black screen displaying the word \"Design\". | Tim C
    p2_apple_hq: { file: V("apple-cook-archive.mp4"), startFrom: 763 },
    // sim=0.539 @10s: A line of unfinished Xiaomi SU7 car bodies moves through a bright, automated factory assembly line. 
    p2_supply_chain: { file: V("xiaomi-factory.mp4"), startFrom: 8 },
  },

  // ── part3 ──
  part3: {
    // sim=0.465 @105s: A light blue Porsche Taycan is prominently displayed in a Porsche dealership showroom. | Porsche, Po
    p3_reveal: { file: V("apple-cook-archive.mp4"), startFrom: 103 },
    // sim=0.554 @396s: A first-person view from inside a Xiaomi SU7 Ultra prototype racing on a track, showing the driver, 
    p3_driving: { file: V("su7-nurburgring.mp4"), startFrom: 394 },
    // sim=0.322 @116s: A robotic arm in a modern factory setting is performing an automated roof assembly on a vehicle chas
    p3_luxury_ev: { file: V("xiaomi-factory.mp4"), startFrom: 114 },
    // sim=0.848 @4890s: Lei Jun, wearing a teal suit, is speaking on stage with his hands clasped together. | Lei Jun, Xiaom
    p3_lei_stage: { file: V("lei-jun-su7-launch.mp4"), startFrom: 4888 },
  },

  // ── part4 ──
  part4: {
    // sim=0.458 @90s: Lei Jun stands on stage as a slide displaying large numbers is shown behind him. | Lei Jun, Xiaomi
    p4_western_media: { file: V("lei-jun-su7-launch.mp4"), startFrom: 88 },
    // sim=0.572 @1065s: Tim Cook stands on a brightly lit stage, gesturing with his hands while speaking to the audience. | 
    p4_split_ceo: { file: V("apple-cook-archive.mp4"), startFrom: 1063 },
    // sim=0.468 @4560s: Lei Jun stands on a dark stage with a large screen displaying text behind him. | Lei Jun, Xiaomi, Mi
    p4_cook_close: { file: V("lei-jun-su7-launch.mp4"), startFrom: 4558 },
    // sim=0.271 @1350s: Tim Cook stands on stage next to a large screen displaying the Core ML logo. | Tim Cook, Apple, Core
    p4_lei_determined: { file: V("apple-cook-archive.mp4"), startFrom: 1348 },
    // sim=0.503 @6180s: Lei Jun, wearing a teal suit jacket, stands on a dark stage and addresses the audience. | Lei Jun, X
    p4_final_narration: { file: V("lei-jun-su7-launch.mp4"), startFrom: 6178 },
    // sim=0.325 @2235s: A black screen displays two app icons, a Clapperboard and Final Cut Pro, side-by-side. | Final Cut P
    p4_ending: { file: V("apple-cook-archive.mp4"), startFrom: 2233 },
  },

} as const;