// Auto-generated by scripts/generate-tts.ts — do not edit manually.
// MiniMax TTS (speech-2.8-hd) with word-level subtitle timing.
// Generated: 2026-04-16T18:29:04.438Z

import type { PartAlignment } from "../../../shared/lib/alignment-types";
export type { WordTiming, LineTiming, PartAlignment } from "../../../shared/lib/alignment-types";

export const alignmentManifest: Record<
  string,
  Record<string, PartAlignment>
> = {
  "cn": {
    "part1": {
      "file": "xiaomi-su7/audio/cn/part1-full.mp3",
      "totalDuration": 81.108,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 10.665,
          "words": [
            {
              "text": "2024年，一家中国手机公司第一年就交付了13.6万辆电动汽车。苹果也试过同样的事。花了十年，花了一百亿美元。然后放弃了。",
              "start": 0,
              "end": 10.665
            }
          ]
        },
        "line2": {
          "startTime": 10.665,
          "endTime": 18.464,
          "words": [
            {
              "text": "从外面看，这像是在追风口。",
              "start": 10.665,
              "end": 12.938004535147392
            },
            {
              "text": "又一家手机公司跳上了电动车的热潮。但在小米内部，故事完全不同。",
              "start": 13.104,
              "end": 18.464
            }
          ]
        },
        "line3": {
          "startTime": 18.464,
          "endTime": 29.252,
          "words": [
            {
              "text": "雷军最好的工程师正在离开。那些把小米做到800亿美元的人，开始向汽车公司投简历。",
              "start": 18.464,
              "end": 25.3802358276644
            },
            {
              "text": "不是为了更高的薪水，而是为了一个不同的未来。",
              "start": 25.524,
              "end": 29.252
            }
          ]
        },
        "line4": {
          "startTime": 29.252,
          "endTime": 44.601,
          "words": [
            {
              "text": "一位传统车企的老板对雷军说了一句话，改变了一切。他说，智能电动汽车不就是一个大号手机带四个轮子吗。",
              "start": 29.252,
              "end": 37.55642630385488
            },
            {
              "text": "这话是从一个造车的人嘴里说出来的，不是搞科技的。这让整个问题变得清晰了。",
              "start": 37.728,
              "end": 44.601
            }
          ]
        },
        "line5": {
          "startTime": 44.601,
          "endTime": 58.923,
          "words": [
            {
              "text": "中国的新能源车渗透率，从2019年不到5%，到2024年飙升到47.9%。",
              "start": 44.601,
              "end": 51.664462585034016
            },
            {
              "text": "这是人类历史上最快的消费品替换速度。到12月份，电动车的销量第一次超过了燃油车。",
              "start": 51.804,
              "end": 58.923
            }
          ]
        },
        "line6": {
          "startTime": 58.923,
          "endTime": 73.748,
          "words": [
            {
              "text": "如果你只做手机，车企会抢走你的用户。如果你只做车，手机公司会抢走你的。这两个行业不是自己要合并的。",
              "start": 58.923,
              "end": 67.64449886621315
            },
            {
              "text": "是智能驾驶、互联生态、软件定义硬件，把它们变成了同一个行业。",
              "start": 67.788,
              "end": 73.748
            }
          ]
        },
        "line7": {
          "startTime": 73.748,
          "endTime": 80.9,
          "words": [
            {
              "text": "而雷军，这个从零开始把小米做到全球前三的工程师，一开始根本不想干这件事。",
              "start": 73.748,
              "end": 80.9
            }
          ]
        }
      }
    },
    "part2": {
      "file": "xiaomi-su7/audio/cn/part2-full.mp3",
      "totalDuration": 123.768,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 13.275,
          "words": [
            {
              "text": "雷军禁止公司讨论造车。禁了两次。他投资了蔚来和小鹏，但只是旁观者。他在一旁看着。看着资金危机，看着破产边缘，看着梦想破碎。他不想参与。",
              "start": 0,
              "end": 13.274693877551021
            }
          ]
        },
        "line2": {
          "startTime": 13.275,
          "endTime": 23.51,
          "words": [
            {
              "text": "用他自己的话说，就我个人角度来讲，我是不想干的。他当时五十岁，在想退休的事。在培养年轻人来接班。造车从来不在他的计划里。",
              "start": 13.428,
              "end": 23.51
            }
          ]
        },
        "line3": {
          "startTime": 23.51,
          "endTime": 31.938,
          "words": [
            {
              "text": "但董事会看到了雷军不愿面对的事实。",
              "start": 23.51,
              "end": 26.366004535147393
            },
            {
              "text": "如果小米不往前走，人才会走掉，竞争力会消退，未来会属于别人。",
              "start": 26.532,
              "end": 31.938
            }
          ]
        },
        "line4": {
          "startTime": 31.938,
          "endTime": 46.455,
          "words": [
            {
              "text": "于是雷军做了工程师该做的事。他对整个汽车行业做了一次全面的调研。七十五天，两百位专家，两百五十场会议。不是看报告。",
              "start": 31.938,
              "end": 42.20995918367347
            },
            {
              "text": "是坐在造了一辈子车的人面前，一个一个请教。",
              "start": 42.372,
              "end": 46.455
            }
          ]
        },
        "line5": {
          "startTime": 46.455,
          "endTime": 67.596,
          "words": [
            {
              "text": "他的发现让他害怕。智能电动车有手机一样的经济模型。研发成本巨大，但一旦做成，复制成本几乎为零。这意味着赢家通吃。",
              "start": 46.455,
              "end": 57.341750566893424
            },
            {
              "text": "他的判断是全球最终只能活五到八家。掰着手指数，特斯拉，比亚迪，丰田，大众。可能已经没有位置了。",
              "start": 57.492,
              "end": 67.596
            }
          ]
        },
        "line6": {
          "startTime": 67.596,
          "endTime": 81.724,
          "words": [
            {
              "text": "然后苹果放弃了。",
              "start": 67.596,
              "end": 69.31544671201813
            },
            {
              "text": "十年，一百亿美元，两千名工程师。全世界最有钱的公司，做不成。",
              "start": 69.51544671201813,
              "end": 75.62678458049886
            },
            {
              "text": "雷军的第一反应是震惊。第二反应是多少有点小窃喜。牌桌上又少了一个对手。",
              "start": 75.78,
              "end": 81.724
            }
          ]
        },
        "line7": {
          "startTime": 81.724,
          "endTime": 93.234,
          "words": [
            {
              "text": "他走进董事会说，这件事需要一百亿美金，十年时间。每一分钱都是小米股东的血汗钱。",
              "start": 81.724,
              "end": 88.34648526077098
            },
            {
              "text": "但如果没有这样的准备，我们很容易打到一半就挂了。",
              "start": 88.488,
              "end": 93.234
            }
          ]
        },
        "line8": {
          "startTime": 93.234,
          "endTime": 103.713,
          "words": [
            {
              "text": "董事会说行，但你来领军。你亲自干。不是找个人来对付，不是搞个子公司。你。双方锁定。没有退路，没有备选方案。",
              "start": 93.234,
              "end": 103.713
            }
          ]
        },
        "line9": {
          "startTime": 103.713,
          "endTime": 114.768,
          "words": [
            {
              "text": "他后来管这条路叫向死而生。不是乐观，不是逞强。只是清醒地接受，成功的概率可能是万分之一。但什么都不做，那就是百分之百的死亡。",
              "start": 103.86,
              "end": 114.768
            }
          ]
        },
        "line10": {
          "startTime": 114.768,
          "endTime": 123.593,
          "words": [
            {
              "text": "现在他有了钱，有了授权。但一个更难的问题在等着他。",
              "start": 114.768,
              "end": 119.16643990929705
            },
            {
              "text": "为什么全世界最强大的公司，总是在这种跨界上失败？",
              "start": 119.304,
              "end": 123.59257142857143
            }
          ]
        }
      }
    },
    "part3": {
      "file": "xiaomi-su7/audio/cn/part3-full.mp3",
      "totalDuration": 113.148,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 13.727,
          "words": [
            {
              "text": "2022年春节。别人都在放假。雷军取消了所有安排。连续二十多天，早上九点到午夜，他让整个管理层坐下来，只问一个问题。我们会怎么死？",
              "start": 0,
              "end": 13.727
            }
          ]
        },
        "line2": {
          "startTime": 13.727,
          "endTime": 29.917,
          "words": [
            {
              "text": "他们研究了失败的案例。",
              "start": 13.727,
              "end": 16.049478458049887
            },
            {
              "text": "微软花七十亿美元买了诺基亚，全部打了水漂。英特尔砸了几十亿做手机芯片，始终做不成。全世界最强大的公司，要钱有钱，要人有人，跨界做新业务照样惨败。",
              "start": 16.2,
              "end": 29.917
            }
          ]
        },
        "line3": {
          "startTime": 29.917,
          "endTime": 43.289,
          "words": [
            {
              "text": "他们找到了三个致命原因。",
              "start": 29.917,
              "end": 32.203038548752836
            },
            {
              "text": "第一个叫偶像包袱。我有品牌，有人才，有钱，怎么可能失败？微软觉得做手机系统很简单。英特尔觉得手机芯片不难。这种傲慢把他们毁了。",
              "start": 32.364,
              "end": 43.289
            }
          ]
        },
        "line4": {
          "startTime": 43.289,
          "endTime": 58.031,
          "words": [
            {
              "text": "第二个叫惯性思维。",
              "start": 43.289,
              "end": 44.849215419501135
            },
            {
              "text": "用从10到100的方法去解决从0到1的问题。就像在短视频时代还在拍电视广告。拍出来的东西像演戏，消费者直接划走。整个路子就是错的，但你看不见，因为你一直就是这么干的。",
              "start": 45,
              "end": 58.03088435374149
            }
          ]
        },
        "line5": {
          "startTime": 58.031,
          "endTime": 72.331,
          "words": [
            {
              "text": "第三个叫认知错误。不承认自己是从零开始。小米内部总有人提世界唯一、世界第一。雷军定了个规矩叫唯一第一罪。你凭什么？拿证据来。拿不出来就收回。",
              "start": 58.176,
              "end": 72.331
            }
          ]
        },
        "line6": {
          "startTime": 72.331,
          "endTime": 84.113,
          "words": [
            {
              "text": "他的战略叫守正出奇。",
              "start": 72.331,
              "end": 74.35318820861677
            },
            {
              "text": "先上牌桌，不要没上桌就把桌子掀了。苹果失败是因为想一上来就颠覆一切。雷军选了另一条路。先把车做好，再谈革命。",
              "start": 74.52,
              "end": 84.113
            }
          ]
        },
        "line7": {
          "startTime": 84.113,
          "endTime": 104.533,
          "words": [
            {
              "text": "然后他做了所有人意想不到的事。不是抄近路，是十倍投入。",
              "start": 84.113,
              "end": 88.90925170068027
            },
            {
              "text": "三千四百名工程师，行业标准只有三四百。六百辆测试车，行业标准是七十到两百。三百个城市，五百四十万公里路测。保时捷前几天发新车，骄傲地说测了三百万公里。小米比他们多了百分之八十。",
              "start": 89.064,
              "end": 104.53297959183674
            }
          ]
        },
        "line8": {
          "startTime": 104.533,
          "endTime": 112.947,
          "words": [
            {
              "text": "方法论定了，钱到位了，团队组好了。接下来三年，才是真正让雷军睡不着觉的部分。把车造出来。",
              "start": 104.688,
              "end": 112.947
            }
          ]
        }
      }
    },
    "part4": {
      "file": "xiaomi-su7/audio/cn/part4-full.mp3",
      "totalDuration": 127.08,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 14.436,
          "words": [
            {
              "text": "雷军借了一百七十辆不同的车。每辆开一两天，问每个车主一样的问题。你为什么买这辆车？喜欢什么？哪里不好？他亲自去4S店。每个季度买两辆新车，就为了体验消费者的感觉。",
              "start": 0,
              "end": 14.435691609977324
            }
          ]
        },
        "line2": {
          "startTime": 14.436,
          "endTime": 28.233,
          "words": [
            {
              "text": "他考了赛车执照，学了漂移，买了一台六轴模拟器。然后让五十多位高管也去学。他的道理很简单。如果你不知道车在极限状态下是什么感觉，你就分不清好车和差车。",
              "start": 14.58,
              "end": 28.233
            }
          ]
        },
        "line3": {
          "startTime": 28.233,
          "endTime": 47.742,
          "words": [
            {
              "text": "他去了黑河做冬测。零下五十度。",
              "start": 28.233,
              "end": 31.000997732426303
            },
            {
              "text": "工程师平时吃三个菜，因为老板来了加了一个。大家可高兴了。然后是吐鲁番。五十多度。车在太阳底下停了一两个小时，车里温度到九十度。",
              "start": 31.14,
              "end": 43.543945578231295
            },
            {
              "text": "门把手烫得不得了。但那儿的西瓜五块钱一个，好吃极了。",
              "start": 43.7439455782313,
              "end": 47.742
            }
          ]
        },
        "line4": {
          "startTime": 47.742,
          "endTime": 67.313,
          "words": [
            {
              "text": "SU7不是靠直觉设计的。雷军的平板里存了上万张车的图片。团队用数学分析比例。轮走比，宽高比。他们算出来好看到底是什么意思。",
              "start": 47.88,
              "end": 60.36521541950113
            },
            {
              "text": "他们选了圆润的线条，因为数据显示超过30%的买家是女性。",
              "start": 60.56521541950113,
              "end": 65.35301587301588
            },
            {
              "text": "整个行业都没想到。",
              "start": 65.52,
              "end": 67.313
            }
          ]
        },
        "line5": {
          "startTime": 67.313,
          "endTime": 87.536,
          "words": [
            {
              "text": "定价争论了三个月。一派坚持十九万九。雷军坚持二十一万五千九。他说二十万出头有豪华感，十九万九显得便宜。",
              "start": 67.313,
              "end": 77.47115646258503
            },
            {
              "text": "最后的妥协是高价加三大件赠送。真皮座椅，高级音响，冰箱。",
              "start": 77.67115646258503,
              "end": 83.89859410430839
            },
            {
              "text": "他跟团队说，你们不当家不知柴米油盐贵。",
              "start": 84.06,
              "end": 87.536
            }
          ]
        },
        "line6": {
          "startTime": 87.536,
          "endTime": 101.899,
          "words": [
            {
              "text": "发布前请了二十多位汽车媒体来看。十八位说会失败。纯电轿车，不是SUV，在这个市场，必死。其中一个跟雷军打赌，说女性买家不会超过5%。",
              "start": 87.536,
              "end": 99.61024943310657
            },
            {
              "text": "实际数字，超过30%。",
              "start": 99.756,
              "end": 101.899
            }
          ]
        },
        "line7": {
          "startTime": 101.899,
          "endTime": 118.97,
          "words": [
            {
              "text": "2024年3月28日，距宣布造车整整三年，提前两天。发布会后二十七分钟，五万订单。内部预期是月销一万就是爆品。连雷军自己都震惊了。",
              "start": 101.899,
              "end": 114.56321088435374
            },
            {
              "text": "他说，比所有人预期的高了三到五倍，包括我自己。",
              "start": 114.732,
              "end": 118.97
            }
          ]
        },
        "line8": {
          "startTime": 118.97,
          "endTime": 126.892,
          "words": [
            {
              "text": "第一年交付13万6854辆。但对雷军来说，SU7从来不是终点。它是打开更大世界的钥匙。",
              "start": 118.97,
              "end": 126.892
            }
          ]
        }
      }
    },
    "part5": {
      "file": "xiaomi-su7/audio/cn/part5-full.mp3",
      "totalDuration": 118.512,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 16.602,
          "words": [
            {
              "text": "当小米手机用户走向SU7，车门自动打开。坐进去，手机自动和车机连接。你可以在车的大屏上开视频会议。你可以在方向盘上控制家里的空调。",
              "start": 0,
              "end": 13.355963718820862
            },
            {
              "text": "这不是功能列表，这是覆盖你一整天的操作系统。",
              "start": 13.55596371882086,
              "end": 16.602
            }
          ]
        },
        "line2": {
          "startTime": 16.602,
          "endTime": 33.207,
          "words": [
            {
              "text": "全球有九亿台小米设备联网。电视，空气净化器，扫地机器人，耳机，手表，手机，现在加上了车。每多一台设备，其他的就更难被替代。每多一个连接，换到竞品的代价就更高。",
              "start": 16.74,
              "end": 33.207
            }
          ]
        },
        "line3": {
          "startTime": 33.207,
          "endTime": 49.712,
          "words": [
            {
              "text": "苹果其实看懂了。CarPlay就是证据，他们知道手机和车必须互联。但造车意味着要征服140年积累的制造复杂度。苹果想跳过学习过程，一上来就颠覆。这个想法花了他们一百亿美元和十年时间。",
              "start": 33.372,
              "end": 49.711727891156464
            }
          ]
        },
        "line4": {
          "startTime": 49.712,
          "endTime": 75.791,
          "words": [
            {
              "text": "小米完全可以为汽车做一个新品牌。就像丰田做了雷克萨斯。内部争论非常激烈。最后是雷军的观点赢了。他说小米汽车是小米不可分割的一部分。",
              "start": 49.86,
              "end": 65.2477097505669
            },
            {
              "text": "人车家全生态，要赢一起赢，要输一起输。",
              "start": 65.44770975056689,
              "end": 68.86553287981859
            },
            {
              "text": "用户对一个二十块充电宝的信任，变成对三十万汽车的信任。这种信任才是真正的护城河。",
              "start": 69.012,
              "end": 75.791
            }
          ]
        },
        "line5": {
          "startTime": 75.791,
          "endTime": 95.309,
          "words": [
            {
              "text": "这不是小米对特斯拉。这是生态对生态。真正重要的问题不是谁造了最好的车。是谁拥有用户生活中的每一个设备。",
              "start": 75.791,
              "end": 84.43453968253968
            },
            {
              "text": "比亚迪赢在规模和价格。特斯拉赢在品牌和自动驾驶。小米赌的是，当护城河变成九亿台联网设备，整个游戏的规则就变了。",
              "start": 84.6,
              "end": 95.30888888888889
            }
          ]
        },
        "line6": {
          "startTime": 95.309,
          "endTime": 112.314,
          "words": [
            {
              "text": "2024年，一个在考虑退休的人，把一百亿美元押在了一个他不想做的产品上。",
              "start": 95.50888888888889,
              "end": 102.97859410430839
            },
            {
              "text": "因为他想明白了，不做这件事，才是唯一比做更危险的选择。三年后，这辆车在中国的月销量超过了特斯拉Model 3。",
              "start": 103.14,
              "end": 112.314
            }
          ]
        },
        "line7": {
          "startTime": 112.314,
          "endTime": 118.319,
          "words": [
            {
              "text": "向死而生。不是口号。在未来二十年的智能设备时代，这可能是唯一有效的战略。",
              "start": 112.314,
              "end": 118.31873015873016
            }
          ]
        }
      }
    }
  },
  "en": {
    "part1": {
      "file": "xiaomi-su7/audio/en/part1-full.mp3",
      "totalDuration": 89.46,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 13.786,
          "words": [
            {
              "text": "In 2024, a Chinese phone company delivered 136,000 electric cars in its first year. Apple tried to do the same thing. They spent ten years and ten billion dollars. Then they quit.",
              "start": 0,
              "end": 13.785532879818595
            }
          ]
        },
        "line2": {
          "startTime": 14.043,
          "endTime": 23.817,
          "words": [
            {
              "text": "rom the outside, this looks like hype chasing.",
              "start": 14.043,
              "end": 16.683537414965986
            },
            {
              "text": "Another phone maker jumping on the EV bandwagon. But inside Xiaomi's headquarters, the story was completely different. L",
              "start": 16.848,
              "end": 23.817
            }
          ]
        },
        "line3": {
          "startTime": 23.875,
          "endTime": 34.934,
          "words": [
            {
              "text": "i Jun's best engineers were leaving.",
              "start": 23.875,
              "end": 25.966321995464853
            },
            {
              "text": "The people who built Xiaomi into an 80 billion dollar company were sending their resumes to car companies. Not for higher pay. For a different future.A t",
              "start": 26.136,
              "end": 34.934
            }
          ]
        },
        "line4": {
          "startTime": 34.991,
          "endTime": 49.681,
          "words": [
            {
              "text": "aditional car executive told Lei Jun something that changed everything.",
              "start": 34.991,
              "end": 39.074004535147395
            },
            {
              "text": "He said a smart electric car is just a big phone with four wheels. That line came from a car guy, not a tech person. And it made the whole problem clear.",
              "start": 39.24,
              "end": 49.08975056689342
            },
            {
              "text": "China",
              "start": 49.289750566893424,
              "end": 49.681
            }
          ]
        },
        "line5": {
          "startTime": 49.76,
          "endTime": 64.832,
          "words": [
            {
              "text": "s EV penetration went from under five percent in 2019 to nearly 48 percent by 2024.",
              "start": 49.76,
              "end": 56.260226757369615
            },
            {
              "text": "That is the fastest consumer technology replacement in human history. By December, electric cars outsold gasoline cars for the first time. If you",
              "start": 56.412,
              "end": 64.832
            }
          ]
        },
        "line6": {
          "startTime": 64.89,
          "endTime": 81.705,
          "words": [
            {
              "text": "only make phones, the car companies will take your users.If you only make cars, the phone companies will take yours.",
              "start": 64.89,
              "end": 71.62556009070295
            },
            {
              "text": "These two industries didn't merge by choice. Smart driving, connected ecosystems, and software defined hardware made them the same industry.",
              "start": 71.784,
              "end": 80.98359183673469
            },
            {
              "text": "And Lei J",
              "start": 81.144,
              "end": 81.705
            }
          ]
        },
        "line7": {
          "startTime": 81.768,
          "endTime": 89.252,
          "words": [
            {
              "text": "n, the engineer who built Xiaomi from nothing into a global top three smartphone company, didn't want to do any of this.",
              "start": 81.768,
              "end": 89.252
            }
          ]
        }
      }
    },
    "part2": {
      "file": "xiaomi-su7/audio/en/part2-full.mp3",
      "totalDuration": 143.856,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 15.501,
          "words": [
            {
              "text": "Lei Jun banned internal discussions about making cars. He did it twice. He'd invested in NIO and XPeng, but only as a spectator. He watched the carnage from the sidelines. The bankruptcies.The broken dreams. He wanted no part of it.",
              "start": 0,
              "end": 15.294829931972789
            },
            {
              "text": "I",
              "start": 15.444,
              "end": 15.501
            }
          ]
        },
        "line2": {
          "startTime": 15.558,
          "endTime": 26.582,
          "words": [
            {
              "text": " his own words, personally, I didn't want to do this. He was fifty years old. He was thinking about retirement. He was training young leaders to take over. The car was never part of the plan.Bu",
              "start": 15.558,
              "end": 26.582
            }
          ]
        },
        "line3": {
          "startTime": 26.64,
          "endTime": 37.467,
          "words": [
            {
              "text": " the board saw what Lei Jun was trying to ignore.",
              "start": 26.64,
              "end": 29.438512471655326
            },
            {
              "text": "If Xiaomi doesn't move forward, the talent walks out the door. The relevance fades. The future belongs to someone else. So ",
              "start": 29.592,
              "end": 37.467
            }
          ]
        },
        "line4": {
          "startTime": 37.531,
          "endTime": 54.333,
          "words": [
            {
              "text": "ei Jun did what an engineer does. He ran a full audit of the auto industry.",
              "start": 37.531,
              "end": 42.332634920634916
            },
            {
              "text": "Seventy five days. Two hundred experts.",
              "start": 42.53263492063492,
              "end": 45.92723809523809
            },
            {
              "text": "Two hundred and fifty meetings. Not reading reports. Sitting across from people who spent their whole lives building cars. What ",
              "start": 46.08,
              "end": 54.333
            }
          ]
        },
        "line5": {
          "startTime": 54.397,
          "endTime": 77.326,
          "words": [
            {
              "text": "e found scared him. Smart EVs have smartphone economics.",
              "start": 54.397,
              "end": 58.007936507936506
            },
            {
              "text": "Huge R&D costs, but almost zero cost to copy once you succeed.",
              "start": 58.20793650793651,
              "end": 62.891247165532874
            },
            {
              "text": "That means winner takes all. His estimate was five to eight companies survive globally. You can count them on your fingers. Tesla. BYD. Toyota. Volkswagen. There might not be room for anyone else.",
              "start": 63.036,
              "end": 76.26425396825397
            },
            {
              "text": "Then App",
              "start": 76.46425396825397,
              "end": 77.326
            }
          ]
        },
        "line6": {
          "startTime": 77.433,
          "endTime": 94.937,
          "words": [
            {
              "text": "e quit. Ten years.",
              "start": 77.433,
              "end": 79.3712380952381
            },
            {
              "text": "Ten billion dollars. Two thousand engineers. The richest company on the planet couldn't do it. Lei Jun's first reaction was shock. His second was a little secret joy.One less giant fighting for a seat at the table.",
              "start": 79.524,
              "end": 94.08740136054422
            },
            {
              "text": "He walked i",
              "start": 94.248,
              "end": 94.937
            }
          ]
        },
        "line7": {
          "startTime": 94.999,
          "endTime": 108.514,
          "words": [
            {
              "text": "to the boardroom and said this requires a hundred billion RMB and ten years. Every yuan is the blood and sweat of our shareholders. But without this level of commitment, we will die halfway through.",
              "start": 94.999,
              "end": 107.39498412698413
            },
            {
              "text": "The board sa",
              "start": 107.59498412698413,
              "end": 108.514
            }
          ]
        },
        "line8": {
          "startTime": 108.591,
          "endTime": 120.833,
          "words": [
            {
              "text": "d fine. But you lead it. Personally.",
              "start": 108.591,
              "end": 111.34949659863945
            },
            {
              "text": "Not a hired CEO. Not a side project. You. Both sides locked in. No exit. No backup plan. He later call",
              "start": 111.492,
              "end": 120.833
            }
          ]
        },
        "line9": {
          "startTime": 120.925,
          "endTime": 134.927,
          "words": [
            {
              "text": "d this path 向死而生. Finding life through death. Not optimism. Not bravado.",
              "start": 120.925,
              "end": 127.51825850340136
            },
            {
              "text": "Just a clear eyed acceptance that the odds are maybe one in ten thousand. But doing nothing is a hundred percent fatal. Now he had the",
              "start": 127.656,
              "end": 134.927
            }
          ]
        },
        "line10": {
          "startTime": 134.982,
          "endTime": 143.666,
          "words": [
            {
              "text": "money and the mandate. But a harder question was waiting.",
              "start": 134.982,
              "end": 138.07463945578232
            },
            {
              "text": "Why do the most powerful companies in the world keep failing at exactly this kind of bet?",
              "start": 138.24,
              "end": 143.666
            }
          ]
        }
      }
    },
    "part3": {
      "file": "xiaomi-su7/audio/en/part3-full.mp3",
      "totalDuration": 132.516,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 17.307,
          "words": [
            {
              "text": "Spring Festival 2022. Everyone else was on vacation. Lei Jun cancelled everything. For twenty straight days, nine AM to midnight, he sat his entire leadership team down and asked one question.",
              "start": 0,
              "end": 16.072698412698415
            },
            {
              "text": "How will we die? ",
              "start": 16.272698412698414,
              "end": 17.307
            }
          ]
        },
        "line2": {
          "startTime": 17.368,
          "endTime": 32.63,
          "words": [
            {
              "text": "hey studied the wreckage.",
              "start": 17.368,
              "end": 18.889433106575964
            },
            {
              "text": "Microsoft bought Nokia for seven billion dollars and wrote it all off. Intel poured billions into mobile chips and never cracked the market.The most powerful companies in the world, with unlimited money, failing completely at new things. Th",
              "start": 19.044,
              "end": 32.63
            }
          ]
        },
        "line3": {
          "startTime": 32.687,
          "endTime": 48.66,
          "words": [
            {
              "text": "y found three killers.",
              "start": 32.687,
              "end": 33.93248072562358
            },
            {
              "text": "The first one is idol complex. We have the brand, the talent, the money, how can we fail? Microsoft thought mobile OS would be easy. Intel thought phone chips were trivial.",
              "start": 34.092,
              "end": 45.89222675736961
            },
            {
              "text": "That arrogance destroyed them. The ",
              "start": 46.092226757369616,
              "end": 48.66
            }
          ]
        },
        "line4": {
          "startTime": 48.734,
          "endTime": 66.342,
          "words": [
            {
              "text": "econd killer is habitual thinking.",
              "start": 48.734,
              "end": 51.22832653061225
            },
            {
              "text": "Using methods built for scaling from ten to a hundred on problems that need you to go from zero to one. It's like filming a Hollywood commercial when your audience lives on TikTok.",
              "start": 51.372,
              "end": 61.10565079365079
            },
            {
              "text": "The whole approach is wrong and you can't see it because it's all you've ever known. The th",
              "start": 61.272,
              "end": 66.342
            }
          ]
        },
        "line5": {
          "startTime": 66.398,
          "endTime": 83.24,
          "words": [
            {
              "text": "rd is cognitive error. Not realizing you're starting from zero.Xiaomi's teams kept proposing world's first and world's best goals.",
              "start": 66.398,
              "end": 73.64111564625851
            },
            {
              "text": "Lei Jun made a rule. He called it the Crime of Firstness. You prove every claim with evidence or you drop it. His stra",
              "start": 73.8,
              "end": 83.24
            }
          ]
        },
        "line6": {
          "startTime": 83.32,
          "endTime": 100.892,
          "words": [
            {
              "text": "egy had a name. 守正出奇. Be orthodox first, then surprise them.",
              "start": 83.32,
              "end": 88.11959183673468
            },
            {
              "text": "Get on the poker table before you try to flip it.",
              "start": 88.31959183673469,
              "end": 90.7273469387755
            },
            {
              "text": "Apple failed because they wanted to change everything on day one. Lei Jun chose humility. Make a great car first. Disrupt later. Then he di",
              "start": 90.864,
              "end": 100.892
            }
          ]
        },
        "line7": {
          "startTime": 100.964,
          "endTime": 122.456,
          "words": [
            {
              "text": " the opposite of cutting corners. He went all in.",
              "start": 100.964,
              "end": 104.49860317460318
            },
            {
              "text": "Three thousand four hundred engineers when the standard was three hundred. Six hundred test vehicles when others used seventy. Five point four million kilometers of testing across three hundred cities.Porsche bragged about three million kilometers for their latest car.",
              "start": 104.652,
              "end": 119.34311111111111
            },
            {
              "text": "Xiaomi beat them by eighty percent. The philosoph",
              "start": 119.484,
              "end": 122.456
            }
          ]
        },
        "line8": {
          "startTime": 122.516,
          "endTime": 132.341,
          "words": [
            {
              "text": " was locked in. The money was committed. The team was massive. Now came the part that would keep Lei Jun awake for three straight years.Actually building the car.",
              "start": 122.516,
              "end": 132.34073469387755
            }
          ]
        }
      }
    },
    "part4": {
      "file": "xiaomi-su7/audio/en/part4-full.mp3",
      "totalDuration": 170.712,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 19.12,
          "words": [
            {
              "text": "Lei Jun borrowed a hundred and seventy different cars. He drove each one for a day or two and asked every owner the same questions. Why did you buy this car? What do you love about it? What's broken?He went to dealerships himself.",
              "start": 0,
              "end": 13.3443537414966
            },
            {
              "text": "Every quarter, he bought two new cars just to understand what the buying experience feels like. H",
              "start": 13.5,
              "end": 19.12
            }
          ]
        },
        "line2": {
          "startTime": 19.178,
          "endTime": 34.643,
          "words": [
            {
              "text": " got a racing license. He learned to drift. He bought a six axis driving simulator.Then he made fifty of his top executives do the same thing. His logic was simple.",
              "start": 19.178,
              "end": 28.678730158730158
            },
            {
              "text": "If you don't know what a car feels like at its limits, you can't tell a good one from a bad one. He ",
              "start": 28.836,
              "end": 34.643
            }
          ]
        },
        "line3": {
          "startTime": 34.701,
          "endTime": 60.526,
          "words": [
            {
              "text": "ent to Heihe for winter testing. Minus fifty degrees.The engineers there normally ate three dish meals.",
              "start": 34.701,
              "end": 40.68266666666667
            },
            {
              "text": "They added a fourth dish because the chairman showed up. Everyone was so happy about the extra dish. Then Turpan in summer. Fifty degrees outside.The car's interior hit ninety degrees after sitting in the sun. The door handles would burn your skin.",
              "start": 40.824,
              "end": 55.22486167800454
            },
            {
              "text": "But the local watermelons were five yuan each and absolutely incredible. The SU7",
              "start": 55.368,
              "end": 60.526
            }
          ]
        },
        "line4": {
          "startTime": 60.591,
          "endTime": 84.023,
          "words": [
            {
              "text": "wasn't designed by gut feeling. Lei Jun had over ten thousand photos of cars saved on his tablet.His team analyzed proportions with math. Wheel to body ratio.",
              "start": 60.591,
              "end": 70.77892970521542
            },
            {
              "text": "Width to height ratio. They figured out what beauty actually means in numbers. They chose rounded lines because data showed over thirty percent of buyers would be women. Nobody in the industry expected that.The pricin",
              "start": 70.92,
              "end": 84.023
            }
          ]
        },
        "line5": {
          "startTime": 84.083,
          "endTime": 115.201,
          "words": [
            {
              "text": " debate lasted three months.",
              "start": 84.083,
              "end": 85.7736507936508
            },
            {
              "text": "One camp wanted 199,000 yuan. Lei Jun held firm at 215,900. His argument was that just over 200,000 feels like a luxury car. 199,000 feels cheap.",
              "start": 85.932,
              "end": 101.71444897959184
            },
            {
              "text": "The compromise was the higher price plus three free accessories. Leather seats, premium sound system, and a fridge. He told his team, you have no idea how much we're losing on every car.",
              "start": 101.88,
              "end": 114.08657596371881
            },
            {
              "text": "Before the la",
              "start": 114.228,
              "end": 115.201
            }
          ]
        },
        "line6": {
          "startTime": 115.276,
          "endTime": 135.204,
          "words": [
            {
              "text": "nch, twenty automotive media people were invited for a preview. Eighteen said it would fail. A pure electric sedan, not an SUV, in this market? Dead on arrival.",
              "start": 115.276,
              "end": 127.24727437641724
            },
            {
              "text": "One of them bet Lei Jun that female buyers would be under five percent.",
              "start": 127.44727437641724,
              "end": 131.72423582766442
            },
            {
              "text": "The real number was over thirty. March 28, 2024.",
              "start": 131.868,
              "end": 135.204
            }
          ]
        },
        "line7": {
          "startTime": 135.274,
          "endTime": 158.06,
          "words": [
            {
              "text": "Exactly three years after the announcement. Two days ahead of schedule.Twenty seven minutes after the launch event, fifty thousand orders came in.",
              "start": 135.274,
              "end": 145.42133333333334
            },
            {
              "text": "The internal prediction had been maybe five thousand a month if they were lucky. Even Lei Jun was stunned. He said the result was three to five times what anyone expected, including himself. First year delive",
              "start": 145.584,
              "end": 158.06
            }
          ]
        },
        "line8": {
          "startTime": 158.12,
          "endTime": 170.516,
          "words": [
            {
              "text": "ies.",
              "start": 158.12,
              "end": 158.35946485260772
            },
            {
              "text": "136,854 cars.",
              "start": 158.55946485260773,
              "end": 163.3356553287982
            },
            {
              "text": "But for Lei Jun, the SU7 was never the destination. It was the key that unlocked something much bigger.",
              "start": 163.476,
              "end": 170.516
            }
          ]
        }
      }
    },
    "part5": {
      "file": "xiaomi-su7/audio/en/part5-full.mp3",
      "totalDuration": 127.548,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 18.413,
          "words": [
            {
              "text": "When a Xiaomi phone user walks toward the SU7, the car unlocks by itself. You sit down and your phone connects to the dashboard. You can take a video call on the car's big screen.You can turn on your home AC from the steering wheel.",
              "start": 0,
              "end": 13.181814058956915
            },
            {
              "text": "This isn't a feature list. It's an operating system for your entire day. N",
              "start": 13.32,
              "end": 18.413
            }
          ]
        },
        "line2": {
          "startTime": 18.482,
          "endTime": 35.248,
          "words": [
            {
              "text": "ne hundred million Xiaomi devices are connected around the world.TVs, air purifiers, robot vacuums, earbuds, watches, phones, and now the car.",
              "start": 18.482,
              "end": 28.254920634920637
            },
            {
              "text": "Every device makes the others harder to leave. Every new connection raises the cost of switching to a competitor. App",
              "start": 28.404,
              "end": 35.248
            }
          ]
        },
        "line3": {
          "startTime": 35.307,
          "endTime": 53.741,
          "words": [
            {
              "text": "e understood this. CarPlay was the proof.They knew the phone and the car had to talk to each other.",
              "start": 35.307,
              "end": 41.09819501133787
            },
            {
              "text": "But building a car means mastering 140 years of manufacturing complexity. Apple wanted to skip the learning curve and flip the table on day one. That cost them ten billion dollars and a decade of work.Xiaomi",
              "start": 41.256,
              "end": 53.741
            }
          ]
        },
        "line4": {
          "startTime": 53.802,
          "endTime": 79.262,
          "words": [
            {
              "text": "could have made a separate brand for the car.",
              "start": 53.802,
              "end": 56.516
            },
            {
              "text": "Like Toyota made Lexus. The internal debate was intense. Lei Jun's argument won. He said Xiaomi Auto is inseparable from Xiaomi. Person, car, home. We win together or we lose together.",
              "start": 56.664,
              "end": 71.03003174603174
            },
            {
              "text": "A customer's trust in a twenty dollar power bank becomes trust in a thirty thousand dollar car. That trust is the real moat. This isn",
              "start": 71.172,
              "end": 79.262
            }
          ]
        },
        "line5": {
          "startTime": 79.323,
          "endTime": 100.474,
          "words": [
            {
              "text": "t Xiaomi versus Tesla. This is ecosystem versus ecosystem.The real question isn't who builds the best car.",
              "start": 79.323,
              "end": 85.77023129251701
            },
            {
              "text": "It's who owns the user across every device in their life. BYD wins on scale and price. Tesla wins on brand and autonomy.Xiaomi is betting that when the moat becomes nine hundred million connected devices, the whole game changes.",
              "start": 85.932,
              "end": 99.60143310657597
            },
            {
              "text": "In 2024, a m",
              "start": 99.756,
              "end": 100.474
            }
          ]
        },
        "line6": {
          "startTime": 100.534,
          "endTime": 117.741,
          "words": [
            {
              "text": "n who was thinking about retirement bet ten billion dollars on a product he never wanted to build. Because he realized that not building it was the only thing more dangerous than building it.",
              "start": 100.534,
              "end": 111.96257596371882
            },
            {
              "text": "Three years later, that car outsold the Model 3 in China.",
              "start": 112.16257596371882,
              "end": 116.56724716553288
            },
            {
              "text": "向死而生. Finding ",
              "start": 116.712,
              "end": 117.741
            }
          ]
        },
        "line7": {
          "startTime": 117.815,
          "endTime": 127.374,
          "words": [
            {
              "text": "ife through death. It's not a slogan. For the next twenty years of the smart device era, it might be the only strategy that works.",
              "start": 117.815,
              "end": 127.374
            }
          ]
        }
      }
    }
  }
};
