// Editor proposal — generated by video-editor skill (Gibney persona)
// Director: gibney (auto-selected based on content scoring)
// Scoring: gibney=92 (billion/million/dollars), morris=43 (bet/promise/risk), curtis=33 (Western narrative)
// Role balance target: literal 4-5, emotional 1-2, implication 2-3, contrast 1-2 per 8-10 line part
// REVIEW BEFORE RENAMING TO broll-manifest.ts

export const brollManifest = {
  part1: {
    // line 2 [contrast] The narration stakes out the outside view: another phone company chasing a trend. The image shows what trend-chasers don't build: a factory floor, tolerances, precision. The document contradicts the dismissal.
    narration2: { file: "xiaomi-su7/videos/official-su7-factory.mp4", startFrom: 0 },
    // line 3 [implication] When narration names the talent migration, skip the individual resumes and show the industry-wide gravitational field pulling them: analysts, rival CEOs, the competitive map.
    narration3: { file: "xiaomi-su7/videos/official-ev-market.mp4", startFrom: 0 },
    // line 4 [literal] The narration quotes a traditional auto executive. The image puts the viewer inside his world: the auto show, the competing brand booths, the context that produced the dismissive worldview.
    narration4: { file: "xiaomi-su7/videos/official-su7-showroom.mp4", startFrom: 120 },
    // line 7 [emotional] Before the triumphalism of the keynote, find the pause. Lei Jun alone on the stage, the weight visible in the stillness before the first slide.
    narration7: { file: "xiaomi-su7/videos/official-leijun-stage.mp4", startFrom: 0 },
  },
  part2: {
    // line 2 [literal] The narration says he invested in NIO and XPeng as a bystander. The image is the literal evidence of what he was watching: NIO, XPeng, Li Auto on Chinese streets. The investments are visible as product.
    narration2: { file: "xiaomi-su7/videos/official-china-ev-streets.mp4", startFrom: 6 },
    // line 3 [emotional] When he names a private hesitation about age and retirement, drop the stage spectacle. The image finds him in a lower-stakes setting, speaking and explaining. Closer to the man contemplating stepping away.
    narration3: { file: "xiaomi-su7/videos/official-leijun-speech.mp4", startFrom: 0 },
    // line 4 [literal] The narration says the board saw what he would not. Show what the board was looking at: the market data, the competitive landscape, the analyst commentary that made the case he could not refuse.
    narration4: { file: "xiaomi-su7/videos/official-ev-market.mp4", startFrom: 40 },
    // line 6 [implication] Seventy-five days, two hundred experts, two hundred and fifty meetings. The narration gives the scale. Cut to the factory floor as the destination of all that research: this is what he was studying.
    narration6: { file: "xiaomi-su7/videos/official-su7-factory.mp4", startFrom: 40 },
    // line 7 [contrast] The narration names Apple's ten years and $10B failure. The image holds on the industry voices. CNBC, CEOs, analysts: the same chorus that tried to warn Xiaomi off. The survivors stand where Apple fell.
    narration7: { file: "xiaomi-su7/videos/official-ev-market.mp4", startFrom: 80 },
    // line 8 [literal] When a commitment is stated ($10B, ten years, shareholder money), anchor in the arena where that commitment was eventually redeemed. Lei Jun on the launch stage, the site of the receipt.
    narration8: { file: "xiaomi-su7/videos/official-leijun-stage.mp4", startFrom: 40 },
    // line 9 [emotional] "You do it. Alone. No backup plan." The narration delivers the verdict. The image finds him in a contained moment, speaking and answering, not the spectacle. The weight of being named.
    narration9: { file: "xiaomi-su7/videos/official-leijun-speech.mp4", startFrom: 40 },
    // line 10 [implication] The closing question: why do the strongest companies fail at crossing over? Do not answer it. Show the graveyard: industry commentary, analyst maps. The answer is in Part 3.
    narration10: { file: "xiaomi-su7/videos/official-ev-market.mp4", startFrom: 160 },
  },
  part3: {
    // line 2 [literal] Chinese New Year, canceled plans, the management team sitting down to ask "how will we die." Anchor in Lei Jun's presence as the one who called the meeting. The image is the authority of the convenor.
    narration2: { file: "xiaomi-su7/videos/official-leijun-stage.mp4", startFrom: 120 },
    // line 3 [contrast] Microsoft, Intel, "the most powerful companies in the world." The narration names the lineage of failure. The image stays in the industry where those giants still walk: CEOs, analysts, the illusion of invulnerability.
    narration3: { file: "xiaomi-su7/videos/official-ev-market.mp4", startFrom: 200 },
    // line 4 [contrast] "Brand baggage." The first fatal sin. The image is the showroom floor where incumbents still project their old confidence: Mercedes, Audi, Ford. Their booths still look the same. That is the evidence.
    narration4: { file: "xiaomi-su7/videos/official-su7-showroom.mp4", startFrom: 0 },
    // line 5 [implication] "Using 10-to-100 methods on 0-to-1 problems." Do not caption the meaning. Let the industry analyst footage play: the people still using the old playbook, unaware they are the case study.
    narration5: { file: "xiaomi-su7/videos/official-ev-market.mp4", startFrom: 280 },
    // line 6 [emotional] The internal reckoning, banning "the world's first" from Xiaomi vocabulary. A quieter, more technical Lei Jun setting. The humility that gets enforced from the top.
    narration6: { file: "xiaomi-su7/videos/official-leijun-speech.mp4", startFrom: 80 },
    // line 7 [literal] "Get on the table before flipping it." The strategy becomes the factory. Show the disciplined execution: robotic arms, assembly lines, the craft of actually making the thing.
    narration7: { file: "xiaomi-su7/videos/official-su7-factory.mp4", startFrom: 80 },
    // line 8 [literal] 3,400 engineers, 600 test cars, 300 cities, 5.4M kilometers. The cascade of numbers becomes visible work. The Nürburgring lap is where numbers turn into a road. Document the scale.
    narration8: { file: "xiaomi-su7/videos/official-su7-driving.mp4", startFrom: 0 },
  },
  part4: {
    // line 2 [literal] 170 borrowed cars, every 4S dealership visit, every season a new car. The narration catalogs the fieldwork. The showroom is the literal site of that fieldwork. The dealer floor is the primary source.
    narration2: { file: "xiaomi-su7/videos/official-su7-showroom.mp4", startFrom: 40 },
    // line 3 [literal] Racing license, drift training, six-axis simulator. The claim is physical competence. The image is competence in motion: the car at limit, the track, the evidence that theory became practice.
    narration3: { file: "xiaomi-su7/videos/official-su7-driving.mp4", startFrom: 40 },
    // line 6 [contrast] 18 of 22 auto-media predicted failure. One bet women would not exceed 5 percent of buyers. The image shows the crowd that proved them wrong: the actual showroom floor, the actual buyers.
    narration6: { file: "xiaomi-su7/videos/official-su7-showroom.mp4", startFrom: 80 },
    // line 8 [implication] 136,854 cars delivered in year one. The number is abstract on paper. Show what it looks like in the wild: Chinese streets, EVs from every brand, the scale of what actually got shipped.
    narration8: { file: "xiaomi-su7/videos/official-china-ev-streets.mp4", startFrom: 50 },
  },
  part5: {
    // line 3 [contrast] Apple understood the phone-to-car connection. CarPlay is the paper trail. But their answer was to skip the learning: $10B and ten years of evidence. Xiaomi's answer is the ecosystem itself, shown working.
    narration3: { file: "xiaomi-su7/videos/official-xiaomi-ecosystem.mp4", startFrom: 0 },
    // line 4 [literal] Internal debate about sub-branding ended with "the car is an inseparable part of Xiaomi." The image is the thesis in product form: the founder explaining it, the ecosystem vocabulary on the record.
    narration4: { file: "xiaomi-su7/videos/official-leijun-speech.mp4", startFrom: 120 },
    // line 5 [contrast] BYD wins on scale. Tesla wins on brand. The narration lists the assumed players. The image shows them all at once in the industry footage and implies they are still running the old playbook.
    narration5: { file: "xiaomi-su7/videos/official-ev-market.mp4", startFrom: 320 },
    // line 6 [literal] The bet paid off: monthly sales surpassed Model 3. Anchor the claim in the car itself, on the road, winning. The product is the verdict.
    narration6: { file: "xiaomi-su7/videos/official-su7-driving.mp4", startFrom: 80 },
    // line 7 [emotional] "Toward death, toward life." The closing thesis. The image is the reveal moment: the car emerging, the decision made visible. Let the audience sit with the stakes without a caption.
    narration7: { file: "xiaomi-su7/videos/official-xiaomi-su7-reveal.mp4", startFrom: 0 },
    ending: { file: "xiaomi-su7/videos/official-china-ev-streets.mp4", startFrom: 130 },
  },
};
