// Auto-generated by scripts/generate-tts.ts — do not edit manually.
// MiniMax TTS (speech-2.8-hd) with word-level subtitle timing.
// Generated: 2026-04-16T10:16:46.183Z

export interface WordTiming {
  text: string;
  /** Seconds from start of the part audio file */
  start: number;
  /** Seconds from start of the part audio file */
  end: number;
}

export interface LineTiming {
  /** When this sentence starts in the part audio (seconds) */
  startTime: number;
  /** When this sentence ends in the part audio (seconds) */
  endTime: number;
  /** Word-level timestamps for caption highlighting */
  words: WordTiming[];
}

export interface PartAlignment {
  /** Path relative to public/, e.g. "audio/cn/part1-full.mp3" */
  file: string;
  /** Total duration of the part audio in seconds */
  totalDuration: number;
  /** Per-line timing data, keyed as line1, line2, ... */
  lines: Record<string, LineTiming>;
}

export const alignmentManifest: Record<
  string,
  Record<string, PartAlignment>
> = {
  "cn": {
    "part1": {
      "file": "audio/cn/part1-full.mp3",
      "totalDuration": 49.464,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 8.521,
          "words": [
            {
              "text": "2010年，小米成立。它的模式很简单：把手机做到极致性价比，把利润留给软件和服务。",
              "start": 0,
              "end": 8.521
            }
          ]
        },
        "line2": {
          "startTime": 8.521,
          "endTime": 19.364,
          "words": [
            {
              "text": "十年后，小米有了5亿台联网设备、370亿美元年营收。",
              "start": 8.521,
              "end": 13.92485260770975
            },
            {
              "text": "但在全球汽车投资人眼里，它仍然只是一家“便宜手机公司”。",
              "start": 14.076,
              "end": 19.364
            }
          ]
        },
        "line3": {
          "startTime": 19.364,
          "endTime": 29.185,
          "words": [
            {
              "text": "2020年，新能源车的渗透率不到6%。到2024年，接近48%。这是人类历史上最快的消费品品类替换速度。",
              "start": 19.364,
              "end": 29.185
            }
          ]
        },
        "line4": {
          "startTime": 29.185,
          "endTime": 34.409,
          "words": [
            {
              "text": "与此同时，中国的电动车市场正在发生一件不可思议的事。",
              "start": 29.34,
              "end": 34.409
            }
          ]
        },
        "line5": {
          "startTime": 34.409,
          "endTime": 42.208,
          "words": [
            {
              "text": "从MIUI到小米手机，从手环到电视，从IPO到造车。这是一家不断突破边界的公司。",
              "start": 34.409,
              "end": 42.208
            }
          ]
        },
        "line6": {
          "startTime": 42.208,
          "endTime": 49.308,
          "words": [
            {
              "text": "当汽车变成一台有四个轮子的智能设备，手机公司和汽车公司的边界，还有意义吗？",
              "start": 42.372,
              "end": 49.307646258503404
            }
          ]
        }
      }
    },
    "part2": {
      "file": "audio/cn/part2-full.mp3",
      "totalDuration": 49.176,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 8.793,
          "words": [
            {
              "text": "2021年初，雷军发现了一个让他彻夜难眠的数据：小米的顶级工程师，开始向汽车公司投简历。",
              "start": 0,
              "end": 8.793
            }
          ]
        },
        "line2": {
          "startTime": 8.793,
          "endTime": 18.727,
          "words": [
            {
              "text": "这不是跳槽，这是行业的引力。",
              "start": 8.793,
              "end": 11.59124716553288
            },
            {
              "text": "智能驾驶、车载操作系统、电池管理，这些岗位的薪资溢价正在虹吸科技人才。",
              "start": 11.79124716553288,
              "end": 18.726893424036284
            }
          ]
        },
        "line3": {
          "startTime": 18.727,
          "endTime": 27.735,
          "words": [
            {
              "text": "从互联网大厂到传统车企，从芯片公司到AI企业，人才正在向汽车行业流动。小米不得不做出选择。",
              "start": 18.864,
              "end": 27.735
            }
          ]
        },
        "line4": {
          "startTime": 27.735,
          "endTime": 33.845,
          "words": [
            {
              "text": "雷军做了一个决定：用75天时间，密集访谈200位汽车行业专家。",
              "start": 27.735,
              "end": 33.845
            }
          ]
        },
        "line5": {
          "startTime": 33.845,
          "endTime": 41.593,
          "words": [
            {
              "text": "小米投入100亿美元，是蔚来、小鹏、理想早期融资的数倍。这是一场不留退路的豪赌。",
              "start": 33.984,
              "end": 41.593
            }
          ]
        },
        "line6": {
          "startTime": 41.593,
          "endTime": 49.012,
          "words": [
            {
              "text": "然后他走进董事会：这需要100亿美元和10年时间。少一分钱，少一年，我都不做。",
              "start": 41.593,
              "end": 49.01180045351474
            }
          ]
        }
      }
    },
    "part3": {
      "file": "audio/cn/part3-full.mp3",
      "totalDuration": 41.904,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 6.456,
          "words": [
            {
              "text": "他们组建了4000人的造车团队，是同类项目行业平均的3到4倍。",
              "start": 0,
              "end": 6.456
            }
          ]
        },
        "line2": {
          "startTime": 6.456,
          "endTime": 12.079,
          "words": [
            {
              "text": "SU7的外形被刻意做圆润，因为数据显示女性用户更喜欢。",
              "start": 6.456,
              "end": 12.078866213151926
            }
          ]
        },
        "line3": {
          "startTime": 12.079,
          "endTime": 20.132,
          "words": [
            {
              "text": "价格、续航、加速、马力，SU7在几乎每一项参数上都压过了Model 3。",
              "start": 12.278866213151927,
              "end": 20.131700680272107
            }
          ]
        },
        "line4": {
          "startTime": 20.132,
          "endTime": 26.956,
          "words": [
            {
              "text": "定价那天，内部吵了6个月。19.9万还是21.59万？",
              "start": 20.268,
              "end": 26.956
            }
          ]
        },
        "line5": {
          "startTime": 26.956,
          "endTime": 35.377,
          "words": [
            {
              "text": "性能与价格的最佳平衡点。21.59万，附赠三大配件。这是小米的答案。",
              "start": 26.956,
              "end": 35.377
            }
          ]
        },
        "line6": {
          "startTime": 35.377,
          "endTime": 41.751,
          "words": [
            {
              "text": "发布会结束27分钟后，5万张订单确认。",
              "start": 35.57707029478458,
              "end": 39.424462585034014
            },
            {
              "text": "第一年交付近14万台。",
              "start": 39.564,
              "end": 41.751
            }
          ]
        }
      }
    },
    "part4": {
      "file": "audio/cn/part4-full.mp3",
      "totalDuration": 39.852,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 8.23,
          "words": [
            {
              "text": "小米的成功，证明了一件事：在智能化时代，汽车行业的入场券，不再是百年的造车经验。",
              "start": 0,
              "end": 8.23
            }
          ]
        },
        "line2": {
          "startTime": 8.23,
          "endTime": 17.489,
          "words": [
            {
              "text": "以SU7为中心，手机、手表、耳机、电视、空调、路由器，全部连接在一起。这就是人车家全生态。",
              "start": 8.23,
              "end": 17.489
            }
          ]
        },
        "line3": {
          "startTime": 17.489,
          "endTime": 25.624,
          "words": [
            {
              "text": "现在，有超过50家中国科技和消费电子公司，正在以不同形式进入汽车产业链。",
              "start": 17.64,
              "end": 25.624
            }
          ]
        },
        "line4": {
          "startTime": 25.624,
          "endTime": 31.391,
          "words": [
            {
              "text": "从欧洲到东南亚，从中东到南美，中国车企正在加速出海。",
              "start": 25.624,
              "end": 31.390702947845806
            }
          ]
        },
        "line5": {
          "startTime": 31.391,
          "endTime": 39.702,
          "words": [
            {
              "text": "真正的问题不是“小米能不能活下去”，而是：当护城河变了，谁拥有定价权？",
              "start": 31.536,
              "end": 39.702
            }
          ]
        }
      }
    }
  },
  "en": {
    "part1": {
      "file": "audio/en/part1-full.mp3",
      "totalDuration": 58.284,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 9.323,
          "words": [
            {
              "text": "In 2010, Xiaomi was founded. The model was simple: make phones at extreme value, keep profits in software and services.",
              "start": 0,
              "end": 9.323
            }
          ]
        },
        "line2": {
          "startTime": 9.402,
          "endTime": 22.76,
          "words": [
            {
              "text": " decade later, Xiaomi had 500 million connected devices and 37 billion dollars in annual revenue.",
              "start": 9.402,
              "end": 17.001496598639456
            },
            {
              "text": "But to global auto investors, it was still just a cheap phone company. I",
              "start": 17.172,
              "end": 22.76
            }
          ]
        },
        "line3": {
          "startTime": 22.838,
          "endTime": 34.482,
          "words": [
            {
              "text": " 2020, new energy vehicle penetration was under 6 percent. By 2024, nearly 48 percent.The fastest consumer category replacement in human history.",
              "start": 22.838,
              "end": 34.092226757369616
            },
            {
              "text": "Mea",
              "start": 34.236,
              "end": 34.482
            }
          ]
        },
        "line4": {
          "startTime": 34.564,
          "endTime": 41.46,
          "words": [
            {
              "text": "while, something extraordinary was happening in China's electric vehicle market. Fro",
              "start": 34.564,
              "end": 41.46
            }
          ]
        },
        "line5": {
          "startTime": 41.542,
          "endTime": 51.414,
          "words": [
            {
              "text": " MIUI to smartphones, from wearables to TV, from IPO to car manufacturing.A company that keeps breaking boundaries.",
              "start": 41.542,
              "end": 50.982077097505666
            },
            {
              "text": "When ",
              "start": 51.12,
              "end": 51.414
            }
          ]
        },
        "line6": {
          "startTime": 51.473,
          "endTime": 58.114,
          "words": [
            {
              "text": " car becomes a smart device on four wheels, does the line between phone companies and car companies still matter?",
              "start": 51.473,
              "end": 58.11369614512472
            }
          ]
        }
      }
    },
    "part2": {
      "file": "audio/en/part2-full.mp3",
      "totalDuration": 55.008,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 9.207,
          "words": [
            {
              "text": "In early 2021, Lei Jun discovered something that kept him up at night: Xiaomi's top engineers were sending resumes to car companies.",
              "start": 0,
              "end": 9.207
            }
          ]
        },
        "line2": {
          "startTime": 9.277,
          "endTime": 19.888,
          "words": [
            {
              "text": "This wasn't job-hopping. It was industry gravity.",
              "start": 9.277,
              "end": 12.694195011337868
            },
            {
              "text": "Smart driving, car OS, battery management — these roles were siphoning tech talent with premium salaries.F",
              "start": 12.852,
              "end": 19.888
            }
          ]
        },
        "line3": {
          "startTime": 19.955,
          "endTime": 29.272,
          "words": [
            {
              "text": "om tech giants to legacy automakers, from chip companies to AI firms, talent was flowing toward the auto industry. Xiaomi had to choose.",
              "start": 19.955,
              "end": 28.982748299319727
            },
            {
              "text": "Le",
              "start": 29.124,
              "end": 29.272
            }
          ]
        },
        "line4": {
          "startTime": 29.346,
          "endTime": 35.107,
          "words": [
            {
              "text": " Jun made a decision: spend 75 days interviewing 200 auto industry experts.Xia",
              "start": 29.346,
              "end": 35.107
            }
          ]
        },
        "line5": {
          "startTime": 35.18,
          "endTime": 46.209,
          "words": [
            {
              "text": "mi committed 10 billion dollars — several times what NIO, XPeng, and Li Auto raised in their early rounds combined. An all-in bet with no exit.",
              "start": 35.18,
              "end": 45.74236734693877
            },
            {
              "text": "Then",
              "start": 45.9,
              "end": 46.209
            }
          ]
        },
        "line6": {
          "startTime": 46.286,
          "endTime": 54.856,
          "words": [
            {
              "text": "he walked into the boardroom: This requires 10 billion dollars and 10 years. Not a penny less, not a year less.",
              "start": 46.286,
              "end": 54.85578231292517
            }
          ]
        }
      }
    },
    "part3": {
      "file": "audio/en/part3-full.mp3",
      "totalDuration": 47.7,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 5.382,
          "words": [
            {
              "text": "They assembled a 4,000-person car team — 3 to 4 times the industry average for similar projects.",
              "start": 0,
              "end": 5.382
            }
          ]
        },
        "line2": {
          "startTime": 5.438,
          "endTime": 10.036,
          "words": [
            {
              "text": "The SU7's design was deliberately rounded — data showed female users preferred it.",
              "start": 5.438,
              "end": 10.035510204081632
            }
          ]
        },
        "line3": {
          "startTime": 10.297,
          "endTime": 19.759,
          "words": [
            {
              "text": "rice, range, acceleration, horsepower — the SU7 beat the Model 3 on nearly every spec. ",
              "start": 10.297,
              "end": 19.759
            }
          ]
        },
        "line4": {
          "startTime": 19.867,
          "endTime": 26.561,
          "words": [
            {
              "text": "he pricing debate lasted 6 months. 199,000 or 215,900 yuan?",
              "start": 19.867,
              "end": 26.28391836734694
            },
            {
              "text": "T",
              "start": 26.483918367346938,
              "end": 26.561
            }
          ]
        },
        "line5": {
          "startTime": 26.638,
          "endTime": 37.24,
          "words": [
            {
              "text": "e perfect balance of performance and price.",
              "start": 26.638,
              "end": 29.948181405895692
            },
            {
              "text": "215,900 yuan, with three premium accessories included. That was Xiaomi's answer. 27",
              "start": 30.096,
              "end": 37.24
            }
          ]
        },
        "line6": {
          "startTime": 37.326,
          "endTime": 47.546,
          "words": [
            {
              "text": "minutes after the launch event ended, 50,000 orders were confirmed.",
              "start": 37.326,
              "end": 43.09205442176871
            },
            {
              "text": "First year deliveries: nearly 140,000 units.",
              "start": 43.292054421768704,
              "end": 47.545795918367354
            }
          ]
        }
      }
    },
    "part4": {
      "file": "audio/en/part4-full.mp3",
      "totalDuration": 45.864,
      "lines": {
        "line1": {
          "startTime": 0,
          "endTime": 9.432,
          "words": [
            {
              "text": "Xiaomi's success proved one thing: in the smart era, the ticket to the auto industry is no longer a century of manufacturing experience.",
              "start": 0,
              "end": 9.431791383219956
            }
          ]
        },
        "line2": {
          "startTime": 9.734,
          "endTime": 21.597,
          "words": [
            {
              "text": "ith the SU7 at the center — phone, watch, earbuds, TV, AC, router — all connected.",
              "start": 9.734,
              "end": 18.14639455782313
            },
            {
              "text": "This is the Person, Car, Home ecosystem. T",
              "start": 18.288,
              "end": 21.597
            }
          ]
        },
        "line3": {
          "startTime": 21.676,
          "endTime": 29.556,
          "words": [
            {
              "text": "day, over 50 Chinese tech and consumer electronics companies are entering the auto supply chain.",
              "start": 21.676,
              "end": 29.240698412698414
            },
            {
              "text": "Fr",
              "start": 29.412,
              "end": 29.556
            }
          ]
        },
        "line4": {
          "startTime": 29.628,
          "endTime": 38.935,
          "words": [
            {
              "text": "m Europe to Southeast Asia, from the Middle East to South America, Chinese automakers are accelerating their global expansion. Th",
              "start": 29.628,
              "end": 38.935
            }
          ]
        },
        "line5": {
          "startTime": 39.007,
          "endTime": 45.717,
          "words": [
            {
              "text": " real question isn't, can Xiaomi survive.It's: when the moat changes, who owns pricing power?",
              "start": 39.007,
              "end": 45.716897959183676
            }
          ]
        }
      }
    }
  }
};
